# Generated by Django 5.0.2 on 2024-03-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_myuser_address_myuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
