# Generated by Django 5.0.2 on 2024-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exibition', '0002_alter_judge_options_remove_owner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
