# Generated by Django 5.0.3 on 2024-03-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exibition', '0003_owner_address_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
